#!/usr/bin/env node

process.env.DATABASE_URL = "postgresql://admin:localpg2024@localhost:5432/surelm";
process.env.QDRANT_URL = "http://localhost:6333";

import { db } from "./lib/db";
import { generateEmbedding } from "./lib/ai/embeddings";
import { searchPoints as qdrantSearch, getCollectionInfo } from "./lib/vector/qdrantStorage";
import { postgresFullTextSearch as pgFTSSearch } from "./lib/retrieval/postgres";
import { applyRRFS } from "./lib/ai/rerank/rrfs";

const TRACE_DIR = "S:\\BackEndSureLM\\trace";
const TIMESTAMP = new Date().toISOString().replace(/[:.]/g, "-");
const TRACE_FILE = `${TRACE_DIR}\\rag-validation_${TIMESTAMP}.md`;

interface TraceStage {
  name: string;
  startTime: number;
  endTime?: number;
  passed: boolean;
  error?: string;
  details: any[];
}

let traceStages: TraceStage[] = [];

function startTraceStage(name: string): TraceStage {
  const stage: TraceStage = { name, startTime: Date.now(), passed: false, details: [] };
  traceStages.push(stage);
  console.log(`\n[${new Date().toISOString()}]Starting: ${name}`);
  return stage;
}

function endTraceStage(stage: TraceStage, success: boolean, error?: string): void {
  stage.endTime = Date.now();
  stage.passed = success;
  if (error) stage.error = error;
  const duration = ((stage.endTime - stage.startTime) / 1000).toFixed(2);
  console.log(`[${success ? "OK" : "FAIL"}] ${stage.name} (${duration}s)`);
}

function addTraceDetail(stage: TraceStage, title: string, content: any): void {
  stage.details.push({ title, content });
}

async function writeTraceFile(allPassed: boolean): Promise<void> {
  try {
    const fs = await import("fs");
    
    let markdown = `# RAG Pipeline Validation Trace\n\n`;
    markdown += `**Timestamp:** ${new Date().toISOString()}\n`;
    markdown += `**Status:** ${allPassed ? "✓ ALL TESTS PASSED" : "✗ SOME TESTS FAILED"}\n\n`;
    markdown += `## Stage Summary\n\n| Stage | Status | Duration |\n|-------|--------|----------|\n`;
    
    for (const stage of traceStages) {
      const status = stage.passed ? "✓ PASS" : "✗ FAIL";
      const duration = stage.endTime ? ((stage.endTime - stage.startTime) / 1000).toFixed(2) + "s" : "N/A";
      markdown += `| ${stage.name} | ${status} | ${duration} |\n`;
    }
    
    for (const stage of traceStages) {
      markdown += `\n## ${stage.name}\n\n`;
      markdown += `**Status:** ${stage.passed ? "✓ PASS" : "✗ FAIL"}\n`;
      markdown += `**Duration:** ${(stage.endTime ? (stage.endTime - stage.startTime) / 1000 : 0).toFixed(2)}s\n\n`;
      
      if (!stage.passed && stage.error) {
        markdown += `**Error:** ${stage.error}\n\n`;
      }
      
      for (const detail of stage.details) {
        markdown += `### ${detail.title}\n\n\`\`\`json\n${JSON.stringify(detail.content, null, 2)}\n\`\`\`\n\n`;
      }
    }
    
    markdown += `\n---\n*Trace generated by rag-validation.ts*\n`;
    
    fs.writeFileSync(TRACE_FILE, markdown);
    console.log(`\n[REPORT] Trace file: ${TRACE_FILE}`);
  } catch (error) {
    console.error("Failed to write trace:", error);
  }
}

async function queryOllamaEmbeddings(text: string): Promise<{embedding: number[], durationMs: number}> {
  const startTime = Date.now();
  
  try {
    const response = await fetch(process.env.OLLAMA_HOST + "/api/embeddings", {
      method: "POST",
      headers: {"Content-Type": "application/json"},
      body: JSON.stringify({
        model: "nomic-embed-text",
        prompt: text
      })
    });
    
    if (!response.ok) {
      throw new Error(`Ollama embeddings failed: ${response.statusText}`);
    }
    
    const data = await response.json();
    
    return {
      embedding: data.embedding,
      durationMs: Date.now() - startTime
    };
  } catch (error: any) {
    console.error("Embedding request error:", error);
    throw error;
  }
}

async function queryOllamaLLM(prompt: string, modelName: string = "qwen2.5-coder:1.5b"): Promise<{response: string, durationMs: number}> {
  const startTime = Date.now();
  
  try {
    const response = await fetch(process.env.OLLAMA_HOST + "/api/generate", {
      method: "POST",
      headers: {"Content-Type": "application/json"},
      body: JSON.stringify({
        model: modelName,
        prompt: prompt,
        stream: false
      })
    });
    
    if (!response.ok) {
      throw new Error(`Ollama LLM failed: ${response.statusText}`);
    }
    
    const data = await response.json();
    
    return {
      response: data.response,
      durationMs: Date.now() - startTime
    };
  } catch (error: any) {
    console.error("LLM request error:", error);
    throw error;
  }
}

async function runQdrantSearch(vector: number[], limit: number = 5): Promise<{results: Array<{id: string, score: number, payload: any}>, durationMs: number}> {
  const startTime = Date.now();
  
  try {
    const results = await qdrantSearch("content_chunks", vector, {limit});
    
    return {
      results,
      durationMs: Date.now() - startTime
    };
  } catch (error) {
    console.error("Qdrant search failed:", error);
    throw error;
  }
}

async function runPostgresFTS(query: string, limit: number = 5): Promise<{results: any[], durationMs: number}> {
  const startTime = Date.now();
  
  try {
    const results = await pgFTSSearch(query, limit);
    
    return {
      results,
      durationMs: Date.now() - startTime
    };
  } catch (error) {
    console.error("PostgreSQL FTS failed:", error);
    throw error;
  }
}

async function hybridRerank(results: Array<{id: string, score: number, source: string, payload?: any}>): Promise<Array<{id: string, score: number, source: string, rank?: number, rerankedScore?: number, relevance?: string}>> {
  const flatResults = results.map(r => ({
    ...r,
    score: r.score || 0,
    source: r.source as "postgres_fts" | "qdrant"
  }));
  
  return applyRRFS(flatResults);
}

async function main() {
  console.log("=" .repeat(60));
  console.log("RAG Pipeline Validation");
  console.log("=" .repeat(60));
  
  try {
    // Check services
    const serviceStage = startTraceStage("Service Health Check");
    
    let qdrantReady, pgReady, ollamaReady;
    
    try {
      qdrantReady = await fetch(process.env.QDRANT_URL + "/collections").then(r => r.ok).catch(() => false);
      addTraceDetail(serviceStage, "Qdrant Collections", {url: process.env.QDRANT_URL, ready: qdrantReady});
      
      if (qdrantReady) {
        const info = await getCollectionInfo("content_chunks");
        addTraceDetail(serviceStage, "Content Chunks Collection Info", info);
      }
    } catch (error: any) {
      serviceStage.error = error.message;
    }
    
    try {
      await db.$queryRaw`SELECT 1`;
      pgReady = true;
      addTraceDetail(serviceStage, "PostgreSQL Status", {connected: true, database: process.env.DATABASE_URL?.split("@")[1]});
    } catch (error: any) {
      serviceStage.error = error.message;
    }
    
    try {
      const modelsRes = await fetch(process.env.OLLAMA_HOST + "/api/tags");
      if (!modelsRes.ok) throw new Error("Ollama API not responding");
      const modelsData = await modelsRes.json();
      ollamaReady = true;
      addTraceDetail(serviceStage, "Available Ollama Models", {list: modelsData.models?.map((m: any) => m.name)});
    } catch (error: any) {
      serviceStage.error = error.message;
    }
    
    if (!qdrantReady || !pgReady || !ollamaReady) {
      endTraceStage(serviceStage, false, `Services not ready - Qdrant: ${qdrantReady}, PG: ${pgReady}, Ollama: ${ollamaReady}`);
      await writeTraceFile(false);
      process.exit(1);
    }
    
    endTraceStage(serviceStage, true);
    
    // Generate realistic insurance policy questions
    const questionStage = startTraceStage("Generate Realistic Questions");
    
    const questions = [
      "What is the waiting period for pre-existing diseases interm insurance plans?",
      "How are maturity benefits calculated in endowment policies?",
      "What are the premium payment terms available forlife insurance policies?",
      "Who is eligible for coverage and what are age limits?",
      "What exclusions apply to critical illness覆盖?"
    ];
    
    addTraceDetail(questionStage, "Generated Questions", questions);
    endTraceStage(questionStage, true);
    
    // Process each question
    let allQuestionsPassed = true;
    const questionResults: any[] = [];
    
    for (const [idx, question] of questions.entries()) {
      console.log(`\n--- Question ${idx + 1}/${questions.length} ---`);
      
      const qStage = startTraceStage(`Question: "${question}"`);
      
      try {
        // Generate embedding
        const embedStartTime = Date.now();
        const {embedding, durationMs: embedDuration} = await queryOllamaEmbeddings(question);
        addTraceDetail(qStage, "Embedding Generation", {
          question: question.substring(0, 100),
          dimension: embedding.length,
          first5Values: embedding.slice(0, 5),
          generationTimeMs: embedDuration
        });
        
        // Qdrant search
        const qdrantResult = await runQdrantSearch(embedding);
        addTraceDetail(qStage, "Qdrant Vector Search Results", {
          query: question,
          topResults: qdrantResult.results.map((r: any, i: number) => ({
            rank: i + 1,
            id: r.id,
            score: parseFloat(r.score.toFixed(4)),
            chunk_id: r.payload?.chunk_id,
            snippet: r.payload?.content?.substring(0, 200),
            category: r.payload?.category
          })),
          totalFound: qdrantResult.results.length,
          searchTimeMs: qdrantResult.durationMs
        });
        
        // PostgreSQL FTS
        const ftsResult = await runPostgresFTS(question);
        addTraceDetail(qStage, "PostgreSQL FTS Results", {
          query: question,
          topResults: ftsResult.results.map((r: any, i: number) => ({
            rank: i + 1,
            id: r.chunk_id || r.id,
            score: parseFloat(r.score.toFixed(4)),
            chunk_id: r.chunk_id,
            snippet: (r.content || "").substring(0, 200)
          })),
          totalFound: ftsResult.results.length,
          searchTimeMs: ftsResult.durationMs
        });
        
        // Hybrid retrieval with RRF
        const combined = [
          ...qdrantResult.results.map((r: any) => ({
            id: String(r.id),
            score: r.score || 0,
            source: "qdrant",
            payload: r.payload
          })),
          ...ftsResult.results.map((r: any) => ({
            id: String(r.chunk_id || r.id),
            score: Number(r.score) || 0,
            source: "postgres_fts",
            payload: {chunk_id: r.chunk_id, content: r.content}
          }))
        ];
        
        const hybridResults = await hybridRerank(combined);
        addTraceDetail(qStage, "Hybrid Retrieval (RRF Fusion)", {
          combinedCount: combined.length,
          afterDeduplication: hybridResults.length,
          top5Results: hybridResults.slice(0, 5).map((r: any, i: number) => ({
            rank: i + 1,
            id: r.id,
            source: r.source,
            score: parseFloat(r.score.toFixed(4)),
            rerankedScore: r.rerankedScore ? parseFloat(r.rerankedScore.toFixed(6)) : undefined,
            relevance: r.relevance
          }))
        });
        
        // Build context for LLM - include chunk_id and category info when content is empty
        const topContext = hybridResults.slice(0, 3);
        const contextText = topContext.map((r: any) => {
          const src = r.source === "qdrant" ? "[VECTOR]" : "[FTS]";
          if (r.payload?.content && r.payload.content.trim().length > 0) {
            return `${src} ${r.payload.content.substring(0, 500)}\n[Score: ${parseFloat(r.score.toFixed(4))}]`;
          } else {
            return `${src} Chunk ID: ${r.id}\nCategory: ${r.payload?.category || 'N/A'}\nPayload: ${JSON.stringify(r.payload).substring(0, 200)}\n[Score: ${parseFloat(r.score.toFixed(4))}]`;
          }
        }).join("\n\n---\n\n");
        
        addTraceDetail(qStage, "Context Assembled for LLM", {
          chunkCount: topContext.length,
          totalChars: contextText.length,
          sourcesUsed: topContext.map((r: any) => r.source),
          contextSnippet: contextText.substring(0, 500) + (contextText.length > 500 ? "..." : "")
        });
        
        // LLM Inference
        const llmPrompt = `You are an insurance policy expert. Answer the following question using ONLY the provided context. If the answer cannot be found in the context, say "I cannot find specific information about this in the provided documents".
        
Context:
${contextText}

Question: ${question}

Answer:`;
        
        addTraceDetail(qStage, "LLM Prompt Sent to Ollama", {
          model: process.env.PRIMARY_MODEL_NAME || "qwen2.5-coder:1.5b",
          promptLengthChars: llmPrompt.length,
          promptFirst500: llmPrompt.substring(0, 500)
        });
        
        const {response, durationMs: llmDuration} = await queryOllamaLLM(llmPrompt);
        addTraceDetail(qStage, "LLM Response", {
          model: process.env.PRIMARY_MODEL_NAME || "qwen2.5-coder:1.5b",
          response: response,
          responseLengthChars: response.length,
          generationTimeMs: llmDuration
        });
        
        questionResults.push({
          question,
          embeddingDimension: embedding.length,
          qdrantResultsCount: qdrantResult.results.length,
          ftsResultsCount: ftsResult.results.length,
          hybridResultsCount: hybridResults.length,
          llmResponse: response,
          timing: {
            embeddingMs: embedDuration,
            qdrantSearchMs: qdrantResult.durationMs,
            ftsSearchMs: ftsResult.durationMs
          }
        });
        
        endTraceStage(qStage, true);
      } catch (error: any) {
        endTraceStage(qStage, false, error.message || String(error));
        allQuestionsPassed = false;
      }
      
      // Small delay between questions
      await new Promise(r => setTimeout(r, 500));
    }
    
    // Summary
    console.log(`\n` + "=".repeat(60));
    console.log("SUMMARY");
    console.log("=".repeat(60));
    
    const summaryStage = startTraceStage("Validation Summary");
    
    addTraceDetail(summaryStage, "Complete Results", {
      totalQuestions: questions.length,
      passedQuestions: questionResults.filter((r: any) => r.llmResponse).length,
      allPassed: allQuestionsPassed && traceStages.every(s => s.passed),
      timingSummary: {
        averageEmbeddingTime: Math.round(questionResults.reduce((sum, r) => sum + r.timing.embeddingMs, 0) / questionResults.length),
        averageQdrantSearchTime: Math.round(questionResults.reduce((sum, r) => sum + r.timing.qdrantSearchMs, 0) / questionResults.length),
        averageFTSTime: Math.round(questionResults.reduce((sum, r) => sum + r.timing.ftsSearchMs, 0) / questionResults.length)
      }
    });
    
    endTraceStage(summaryStage, allQuestionsPassed);
    
    const finalSuccess = allQuestionsPassed && traceStages.every(s => s.passed);
    await writeTraceFile(finalSuccess);
    
    console.log(`\nTotal stages: ${traceStages.length}`);
    console.log(`Passed: ${traceStages.filter(s => s.passed).length}`);
    console.log(`Failed: ${traceStages.filter(s => !s.passed).length}`);
    
    if (finalSuccess) {
      console.log("\n✓ RAG Pipeline Validation Successful!");
    } else {
      console.log("\n✗ Some validations failed. Check trace file for details.");
      process.exit(1);
    }
    
  } catch (error: any) {
    console.error("Fatal error:", error);
    await writeTraceFile(false);
    process.exit(1);
  }
}

main().catch(error => {
  console.error("Fatal error in main:", error);
  process.exit(1);
});
